### ISSUE TITLE
Higher release debounce delay makes key presses overlap

### ISSUE THREAD

**Issue by Gravemind** [keyboardio/avr_keyscanner#11]
It's probably a non-issue for a lot of people, but important enough to me that I think it's something to think about before a debouncer from `f/configurable-scanners-and-debouncers` goes mainstream.

If the debounce release delay is higher than the press delay then it makes rapid successive key strokes overlap, which is most critical for key sequences using modifiers.

It took a long time to discover this: at first I found key sequences like `Ctrl-X O` would often fail, not often enough to make it a clear issue instantly, but enough to feel like it happened way more often than "since I flashed this or that debouncer".
Then I discovered I was actually because it was typing `Ctrl-X Ctrl-O` instead of `Ctrl-X O`.
Then thinking about it, I found it could be explained by the debouncer having a release delay higher than press: it could make the `Ctrl` press overlap the `O` press even if physically not when **the real time between `release Ctrl` and `press O` was shorter that `release delay - press delay`**.

As an emacs user, those kinds of key sequences happens a lot. **Non-emacs users might never see this issue**. But to test this, one could type in a browser `Ctrl-F L` very fast, which should search `l`, but if the url bar is focused then it means `Ctrl-F Ctrl-L` happened.

I find key sequences which uses both hands are really sensible to this delay difference. And testing from 0 to 10 milliseconds difference between press and release delay, you can feel the overlap happening way more easily than, for example, feel an additional 10 ms latency on both release and press delay.
But I'm pretty sure in every-day typing it's unconscious, and **those kind of delays are only hit because of muscle memory**, which makes this issue more pronounced as you get used to the keyboard.

**Comment by obra** [comment]
I -suspect- that this was due to me having screwed up the runloop, halving the scan speeds. I'd be curious to know if you still see this.

**Comment by Gravemind** [comment]
It's still an issue for me, and the more I test, the more I have it. (but still corner-use-case, see at the end)

Unless I missed something, **all debouncers that retards releases more than presses has the issue**. `split-counter` with delays of 2 and 17 has the issue too for example.

For example, if a debouncer retards presses by 1ms, and releases by 8ms, then if you physically _release_ a key and less than 7ms later _press_ another one, both keys will be registered as pressed at the same time for a moment. It seems inherent to having asymmetric delays.

(And I think 7ms between a release and a press is long when you're dealing with key sequences with modifiers using both hands.)

At the end, if you have 16 release latency for debouncing, and don't want to have press overlap, then you must also introduce a 16 press latency (or very close).

**I still cannot see problematic use-cases other than the "rapid-key-sequences-with-modifiers"**, but it's a every-day use-case for me, so I will continue to prefer more press latency rather than this issue (`split-counter` with 17 17 delays is the one that works best so far).

**Comment by obra** [comment]
I agree 100% with the -theory- of what you're saying. And I believe you're seeing the issue. 

I'm just surprised that it's actually possible to hit that second key that fast. It's -really- not a lot of time.

It -may- be the case that if your control key has the lubrication problem, it's physically sticking, so releasing long after you actually want it to be.

**Comment by Gravemind** [comment]
I forgot about this, probably means I might have overdramatize the issue. Also, I use evil vim binding in emacs for a while now... Closing the issue.
