### ISSUE TITLE
TWI probably doesn't handle repeated start correctly

### ISSUE THREAD

**Issue by tlyu** [keyboardio/avr_keyscanner#17]
This could actually be serious and be interfering with normal operation, to some extent.

The ATtiny TWI implementation doesn't seem to handle repeated starts in receive mode. If it gets one, it seems to loop long enough to miss the next start condition, so effectively it will NAK the next transaction, if it's addressed to it. Register reads seem likely to be particularly problematic. (Write register address, issue repeated start, then read.) It also seems to be the problem that this code

https://github.com/keyboardio/Kaleidoscope/blob/6f11d89152ea274357afad9f621854d1f38bbf00/plugins/Kaleidoscope-Hardware-Keyboardio-Model01/src/kaleidoscope/device/keyboardio/Model01.cpp#L116

might be working around by alternating hands. (The ignored start condition is addressed to the other hand.)

Much of the code in the Model 01 driver seems to use repeated starts. I think some of it is working by accident, because the read operations all send stops, even though (almost?) none of the write operations seems to do so. (This being a polled keyboard, as I recall, read operations probably happen frequently.)

I was trying to add some LED prompting to the flasher sketch, and ran into a problem where I couldn't send multiple LED commands back-to-back using repeated starts without some of them getting ignored. (`twi_writeTo(..., true, false)` on all except the last command) If I always used `sendStop=true`, they would all execute with no problem.

It seems to be a problem with `twi-slave.c` mishandling repeated starts in receive mode by looping until a stop condition is detected. (I think another start condition would break out of the loop, but not before missing the ack of the address.) Sending four LED commands in a row, with `sendStop=false` on the first three, resulted in the first one being read and executed, the second one being NAKed in the address, the third one being read and executed, and the fourth one being NAKed in the address.

The problem is likely here: 

https://github.com/keyboardio/avr_keyscanner/blob/0c8e4401776b7407071c4b1783533dd454a17ec4/firmware/twi-slave.c#L130

because `TWI_Stop()` loops until `TWSTO` is clear, which is not actually documented in the datasheet, and is probably wrong for this situation. Clearing the interrupt flag and not looping, as in

https://github.com/keyboardio/Kaleidoscope/blob/6f11d89152ea274357afad9f621854d1f38bbf00/plugins/Kaleidoscope-Hardware-Keyboardio-Model01/src/kaleidoscope/device/keyboardio/twi.c#L508

seems to allow repeated starts to work correctly.

I think this problem would only be obvious when the TWI bus is relatively quiescent (such as in the ATtiny flashing sketch), and cause subtle (but possibly serious) misbehavior in normal operation.

**Comment by obra** [comment]
Thank you! I've been trying to uncover the cause of that failure for years.
Literal years. But I didn't suspect the twi_slave library as my
understanding was that it was a straight port from the vendor's recommended
implementation. Digging into the source code provided with AVR311 (
https://www.microchip.com/en-us/application-notes/an2565), it looks like
it's more heavily modified than I would have guessed from the comments.
