### ISSUE TITLE
use intelhex library

### ISSUE THREAD

**Issue by tlyu** [keyboardio/avr_keyscanner#24]
Maybe use the [intelhex library](https://pypi.org/project/intelhex/) instead of custom code to manipulate/edit `.hex` files? Or do you prefer to keep Python 2 compatibility in the tools? (the stable intelhex library requires Python 3)

I'm willing to work on a PR for this.

**Comment by tlyu** [comment]
A quick draft has `make_factory_firmware.py` down to about a dozen lines, five of which are the actual hex file manipulation.

**Comment by obra** [comment]
<3 This is incredibly desirable. Thank you.

Python 2 support is an anti-goal.
